[general]
import = [
    "~/.config/alacritty/dank-theme.toml"
]

[window]
padding.x = 10
padding.y = 10

dynamic_padding = true

#opacity = 0.8
#blur = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
