[general]
import = [
    "~/.config/alacritty/dank-theme.toml"
]

[window]
padding.x = 10
padding.y = 10

dynamic_padding = true

#opacity = 0.8
#blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 12
